### ISSUE TITLE
xmpp server

### ISSUE THREAD

**Issue by norayr** [kfv/dotfiles#1]
hello!

i miss talking to you sometimes, so it would be great if you installed xmpp server. that is my issue.

thank you!

**Comment by kfv** [comment]
Hello Norayr,

Same here mate, I miss you too. Roger that, I will take care of it soon.

Cheers

**Comment by norayr** [comment]
yay!

**Comment by kfv** [comment]
Hello, Norayr!

I am not planning to host an XMPP server in the near future. Therefore, I am closing this issue as "Not Planned." However, I assure you that I'd run a server if I ever find the time (and a good reason) to do so.

Cheers
